INSERT INTO c_causas (descripcion,estado_id) VALUES('Sin Causa',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Accidente vehicular',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Acometida rota',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Acopladores sucios',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Bote en mal estado',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Clean up',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Daño interno de F.O.',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Desagregacion',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Empalme desgradado',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Factor climatico',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Falla en jumper',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Falla hardware',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('F.O. suelta u holgada',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Folio duplicado',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Folio mal asignado',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Implementacion 1N.',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Implementacion 2N',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Incendio',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Induccion electrica',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Intermitencia',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Mala Construccion',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Mala manipulacion',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Mordedura de roedor(Nido de ave/Nido de Hormigas',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Mantenimiento correctivo PI',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('No determinada por personal',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Obra publica',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Poda de arboles',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Saturacion',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Sin daño',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Splitter dañado',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Sustitucion de splitter',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Trabajos de CFE/Cambio de posteria',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Trabajos de otros carriers',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Vandalismo',1);
INSERT INTO c_causas(descripcion,estado_id) VALUES('Vehiculo con exceso de dimensiones',1);