INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("TX",1,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("TX",2,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("Miramontes",3,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("Granjas Esmeralda",3,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("Culhuacan",3,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("Cerro de la Estrella",3,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("Ampliacion Cerro de la Estrella",3,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("San Lorenzo Tezonco",3,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("Santa Maria Acatitla",4,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("Santa Martha Acatitla Sur",4,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("Ixtlahuaca",4,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("Palmitas",4,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("Constitucion",4,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("TX",5,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("Cuernavaca 1",6,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("Cuernavaca 2",6,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("Cuernavaca 3",6,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("Ampliacion Cuernavaca 2",6,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("Ocotepec",6,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("Ampliacion Ocotepec",6,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("Tejalpa",6,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("Ampliacion Tejalpa",6,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("Temixco",7,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("Xochitepec",7,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("Jiutepec",7,1);
INSERT INTO c_clusters(descripcion,distrito_id,estado_id) VALUES("San Jose Cumbres",7,1);
