INSERT INTO c_despachos(Nombre,estado_id) VALUES('FRANCO SOSA ABEL',1);
INSERT INTO c_despachos(Nombre,estado_id) VALUES('MARTINEZ SOSA ELIZABETH KIREINA',1);
INSERT INTO c_despachos(Nombre,estado_id) VALUES('AGUILERA SOTO ALFREDO',1);
INSERT INTO c_despachos(Nombre,estado_id) VALUES('RECILLAS MORENO CLAUDIA STEPHANY',1);
INSERT INTO c_despachos(Nombre,estado_id) VALUES('GONZALEZ ANGUIANO LEI CARRIE',1);