INSERT INTO c_justificacion_pausas(descripcion,estado_id) VALUES("Acero inducido",1);
INSERT INTO c_justificacion_pausas(descripcion,estado_id) VALUES("Actividad Programada/No autorizado hasta ventana de mtto",1);
INSERT INTO c_justificacion_pausas(descripcion,estado_id) VALUES("Asalto o Vandalismo",1);
INSERT INTO c_justificacion_pausas(descripcion,estado_id) VALUES("Autoridades de gobierno no permiten laborar",1);
INSERT INTO c_justificacion_pausas(descripcion,estado_id) VALUES("En espera de acceso a la OLT",1);
INSERT INTO c_justificacion_pausas(descripcion,estado_id) VALUES("En espera de apoyo para depuracion",1);
INSERT INTO c_justificacion_pausas(descripcion,estado_id) VALUES("En espera de datos de ctes",1);
INSERT INTO c_justificacion_pausas(descripcion,estado_id) VALUES("En espera de Ingenierias",1);
INSERT INTO c_justificacion_pausas(descripcion,estado_id) VALUES("En espera de Validacion por TPE/NOC",1);
INSERT INTO c_justificacion_pausas(descripcion,estado_id) VALUES("Imputable a instafibra",1);
INSERT INTO c_justificacion_pausas(descripcion,estado_id) VALUES("Ingenieria NO coincide",1);
INSERT INTO c_justificacion_pausas(descripcion,estado_id) VALUES("Lluvia/factor climatico",1);
INSERT INTO c_justificacion_pausas(descripcion,estado_id) VALUES("Mercado ambulante o calle cerrada",1);
INSERT INTO c_justificacion_pausas(descripcion,estado_id) VALUES("Permiso especial para trabajos en zona",1);
INSERT INTO c_justificacion_pausas(descripcion,estado_id) VALUES("Problemas con permisos (permisos  no validos)",1);
INSERT INTO c_justificacion_pausas(descripcion,estado_id) VALUES("Problemas de acceso por arrendatario",1);
INSERT INTO c_justificacion_pausas(descripcion,estado_id) VALUES("Problemas de acceso por infraestructura",1);
INSERT INTO c_justificacion_pausas(descripcion,estado_id) VALUES("Sin trayectorias",1);
INSERT INTO c_justificacion_pausas(descripcion,estado_id) VALUES("Trabajos de CFE (no permiten laborar)",1);
INSERT INTO c_justificacion_pausas(descripcion,estado_id) VALUES("Vecinos no permiten trabajar",1);
INSERT INTO c_justificacion_pausas(descripcion,estado_id) VALUES("Zona acordonada por protección civil",1);
INSERT INTO c_justificacion_pausas(descripcion,estado_id) VALUES("Zona de alto riesgo",1);
INSERT INTO c_justificacion_pausas(descripcion,estado_id) VALUES("Zona de dificil acceso",1);