INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('CINCHOS PANDIUT',1,'CINP01',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('TANJENTES',1,'TJ001',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('PREFORMADOS AMARILLOS 1/4',1,'PREA1.4',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('PREFORMADOS NEGRO 1/16',1,'PREN1.16',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('PREFORMADOS MORADOS 1/16',1,'PREM1.16',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('FLEJES 5/8',1,'FLE5.8',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('NEOPRENO',1,'NOFRE',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('HEBILLAS',1,'HEB001',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('HERRAJES DE PASO',1,'HPSO01',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('HERRAJES TIPO D',1,'HTD001',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('HERRAJES TIPO J',1,'HTJ001',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('HERRAJES TANGENTES',1,'HTNG01',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('MANGAS TECNO',1,'MGTEC1',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('BRAZOS HERRAJE TIPO D 60 CM',1,'BZOTD60',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('BRAZOS HERRAJES TANGENTE 60 CM',1,'BZOT60',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('BRAZOS C/HERRAJES TANGENTE 100CM',1,'BZOCHT100',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('BRAZOS C/HERRAJES TIPO D 100 CM',1,'BZCHTD100',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('BRAZOS C/ HERRAJES TIPO J 100 CM',1,'BZOCHTJ100',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('PROTECTORES',1,'PROTEC01',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('MECATES',1,'MEC001',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('FIBRA 96 MTS',2,'FB096',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('FIBRA 24 MTS',2,'FB024',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('ACERO MTS',2,'AC001',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('MEXFO 1N',2,'MX001',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('RAQUETAS',2,'RQ001',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('ETIQUETAS',2,'ETQA01',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('MEXFOS 24 MINI',2,'MX002',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('SPLITTER 1N 1X8',2,'SP1NX8',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('SPLITTER 2N 1X8',2,'SP2NX8',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('SPLITTER 2N 1X16',2,'SP2NX16',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('CAJAS N1',2,'CJ0N1',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('CAJAS N2 FIBER HOME',2,'CJN2',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('CAJA DE DERIVACION ',2,'CJDER01',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('BOTES DE 2N CIERRE',2,'BT2N01',1);
INSERT INTO c_materiales(descripcion,tipo_material,codigo,estado_id) VALUES('CIERRE 96 ',2,'BTDE1N',1);
